### ISSUE TITLE
Could not install 'weka' by: gem 'weka'

### ISSUE THREAD

**Issue by hailiangwangutd** [paulgoetze/weka-jruby#11]
Could not find gem 'weka' in any of the gem sources listed in your Gemfile or
available on this machine.

**Comment by paulgoetze** [comment]
Hey @hailiangwangutd, did you make sure you are in the JRuby environment before? 

Else could you provide any detailed information on how you tried to install the gem (like e.g. your gemfile)?

**Comment by paulgoetze** [comment]
@hailiangwangutd Do you still need help with this?

**Comment by hailiangwangutd** [comment]
Thank you so much! Done.
