### ISSUE TITLE
Wrong version tag in tag release.

### ISSUE THREAD

**Issue by manzha** [paulgoetze/weka-jruby#29]
I am not sure if this should be here but on the info of Release tag 0.7.0 says weka-dev v3.9.3 instead of v3.9.2. I know it is a minor thing, and does not affect functionality, but rather documentation.

Link: https://github.com/paulgoetze/weka-jruby/releases

**Comment by paulgoetze** [comment]
You are absolutely right, @manzha. Thanks for reporting. Of course we don’t want to confuse anyone ;). I changed it.
